CREATE VIEW VW_ERROR AS

WITH ERROR_AGG AS (
    SELECT 
        ERROR_CATEGORY_L1,
        ERROR_CATEGORY_L2,
        COUNT(*) AS ERROR_COUNT
    FROM TRANSACTIONS_ENHANCED
    WHERE ERROR_CATEGORY_L1 IS NOT NULL
    GROUP BY 
        ERROR_CATEGORY_L1,
        ERROR_CATEGORY_L2
),

TOTAL_ERROR AS (
    SELECT
        ERROR_CATEGORY_L1,
        SUM(ERROR_COUNT) AS TOTAL_COUNT
    FROM ERROR_AGG
    GROUP BY ERROR_CATEGORY_L1
),

RANKED_ERROR AS (
    SELECT
        A.ERROR_CATEGORY_L1,
        A.ERROR_CATEGORY_L2,
        A.ERROR_COUNT,
        (A.ERROR_COUNT * 100.0 / B.TOTAL_COUNT) AS ERROR_PERCENT,
        ROW_NUMBER() OVER (
            PARTITION BY A.ERROR_CATEGORY_L1
            ORDER BY A.ERROR_COUNT DESC
        ) AS RN
    FROM ERROR_AGG A
    JOIN TOTAL_ERROR B
        ON A.ERROR_CATEGORY_L1 = B.ERROR_CATEGORY_L1
)

SELECT
    ERROR_CATEGORY_L1,
    ERROR_CATEGORY_L2,
    ERROR_COUNT,
    ERROR_PERCENT
FROM RANKED_ERROR
WHERE RN = 1
ORDER BY ERROR_COUNT DESC