CREATE VIEW VW_ERRORBYHOUR AS
WITH NEXT_EVENT_TIME AS (
	SELECT 
			SESSION_ID,
			EVENT_ID,
			EVENT_TIMESTAMP,
			LEAD(EVENT_TIMESTAMP) OVER (PARTITION BY SESSION_ID ORDER BY EVENT_TIMESTAMP) AS NEXT_EVENT
		FROM EVENT_LOGS
),
AUTHENTICATION_LOGS AS (
	SELECT 
		DATEPART(HOUR, EVENT_TIMESTAMP) AS EVENT_HOUR, 
		AVG(CAST(DATEDIFF(SECOND, EVENT_TIMESTAMP, NEXT_EVENT) AS FLOAT)) AS AVG_AUTH_TIME_SEC
	FROM NEXT_EVENT_TIME
	WHERE EVENT_ID IN (25,30)
	GROUP BY DATEPART(HOUR, EVENT_TIMESTAMP)
),
BYHOUR AS (
	SELECT
		DATEPART(HOUR, TRANSACTION_DATE) AS TRANS_HOUR,
		SUM(CASE WHEN STATUS = 'FAILURE' THEN 1 ELSE 0 END) AS TOTAL_FAILURE,
		COUNT(*) AS TOTAL_TRANSACTIONS,
		100.0 * SUM(CASE WHEN STATUS = 'FAILURE' THEN 1 ELSE 0 END) / COUNT(*) AS FAILURE_RATE
	FROM TRANSACTIONS_ENHANCED
	GROUP BY DATEPART(HOUR, TRANSACTION_DATE)
)

SELECT 
    H.TRANS_HOUR AS [Hour_Of_Day],
    H.TOTAL_TRANSACTIONS,
    H.TOTAL_FAILURE,
    ROUND(H.FAILURE_RATE, 2) AS FAILURE_RATE_PERCENT,
    ROUND(A.AVG_AUTH_TIME_SEC, 2) AS AVG_AUTH_TIME_SEC
FROM BYHOUR H
LEFT JOIN AUTHENTICATION_LOGS A ON H.TRANS_HOUR = A.EVENT_HOUR
ORDER BY TRANS_HOUR