CREATE VIEW VW_FAILURERATE AS
WITH BASE AS (
	SELECT
		MONTH(TRANSACTION_DATE) AS TRANS_MONTH,
		COUNT(CASE WHEN STATUS = 'FAILURE' THEN 1 END) AS TOTAL_FAILURE,
		COUNT(*) AS TOTAL_TRANSACTIONS,
		CAST(COUNT(CASE WHEN STATUS = 'FAILURE' THEN 1 END) AS DECIMAL(10,2))*100.0/ COUNT(*) AS FAILURE_RATE
	FROM TRANSACTIONS_ENHANCED
	GROUP BY MONTH(TRANSACTION_DATE)
)

SELECT TRANS_MONTH, TOTAL_FAILURE, TOTAL_TRANSACTIONS, FAILURE_RATE,
		FAILURE_RATE - LAG(FAILURE_RATE) OVER(ORDER BY TRANS_MONTH ASC) AS FAILURE_RATE_MOM
FROM BASE