CREATE VIEW VW_Retry_payment AS
WITH RETRY_ATTEMPTS AS (
    SELECT
        TRANSACTION_ID,
        STATUS,
        ROW_NUMBER() OVER(PARTITION BY TRANSACTION_ID ORDER BY TRANSACTION_DATE) AS ATTEMPT_NO
    FROM TRANSACTIONS_ENHANCED
)

SELECT
    ATTEMPT_NO,
    COUNT(*) AS TOTAL_ATTEMPTS,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    100.0 * SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) / COUNT(*) AS SUCCESS_RATE
FROM RETRY_ATTEMPTS
GROUP BY ATTEMPT_NO
ORDER BY ATTEMPT_NO